# Generated by Django 5.1 on 2024-08-29 04:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Dialise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('contato', models.CharField(max_length=20)),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('diagnostico_principal', models.CharField(max_length=200)),
                ('comorbidades', models.TextField()),
                ('data_inicio_dialise', models.DateField()),
                ('medicamentos', models.TextField()),
                ('alergias', models.TextField()),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_acesso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.acesso')),
                ('tipo_dialise', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.dialise')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.sexo')),
            ],
        ),
    ]
