# Generated by Django 5.1 on 2024-08-29 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='nome_completo',
            new_name='nome',
        ),
    ]
