# Generated by Django 5.1 on 2024-08-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_nome_completo_paciente_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='mostrar',
            field=models.BooleanField(default=True),
        ),
    ]
