# Generated by Django 5.1 on 2024-08-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_paciente_mostrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
